### ISSUE TITLE
It returns an empty object

### ISSUE THREAD

**Issue by kopax** [swestmoreland/office-document-properties#3]
Hi, and thanks for sharing,

I have created a .docx document on Google Docs, and downloaded it,

I have run the following test:

```
  it.only('should detect meta data from .docx', (done) => {
    getDocumentProperties.fromFilePath(join(__dirname, 'test.docx'), (data, err) => {
      console.log(err);
      console.log(data);
      expect(true).toEqual(false);
    });
  });

```

I have the following result:

```
  ● convert docx to latex › should detect meta data from .docx

    expect(received).toEqual(expected) // deep equality

    Expected: false
    Received: true

      12 |       console.log(err);
      13 |       console.log(data);
    > 14 |       expect(true).toEqual(false);
         |                    ^
      15 |     });
      16 |   });
      17 | 

      at toEqual (src/docx2latex/tests/convert-docx2latex.test.js:14:20)
      at ZipFile.<anonymous> (node_modules/office-document-properties/index.js:63:9)
      at Immediate.<anonymous> (node_modules/yauzl/index.js:246:12)

  console.log src/docx2latex/tests/convert-docx2latex.test.js:12
    {}

  console.log src/docx2latex/tests/convert-docx2latex.test.js:13
    null
```

It seems not to be OK.

**Comment by swestmoreland** [comment]
I've updated the test suite. The test above does not appear to have originated from the test suite included in the package.
